name: docker-publish

on:
  push:
    tags:
      - v*

jobs:

  build:
    name: Build and publish '${{ matrix.project }}' to Docker Registry

    strategy:
      fail-fast: true
      matrix:
        project: [ api, ssh, gateway, ui, cli ]

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Get release version
      id: get_version
      run: echo RELEASE_VERSION=$(echo ${GITHUB_REF:10}) >> $GITHUB_ENV

    - name: Build and publish '${{ matrix.project }}' to Docker Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: shellhubio/${{ matrix.project }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.RELEASE_VERSION }}"
        dockerfile: ${{ matrix.project }}/Dockerfile
